services:
  user_service:
    build: ./user_service
    ports:
      - "5000:5000"
    depends_on:
      - db
    command: sh -c "while ! nc -z db 5432; do sleep 1; done; python app.py"
    volumes:
    - ./user_service:/app
    - ./user_service/migrations:/app/migrations
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=user_service_db
    ports:
      - "5435:5432"
    volumes:
      - user_service_data:/var/lib/postgresql/data
  track_service:
    build: ./track_service
    ports:
      - "5001:5001"
    depends_on:
      - track_db
    command: sh -c "while ! nc -z track_db 5432; do sleep 1; done; flask run --host=0.0.0.0 --port=5001"
    environment:
      FLASK_ENV: development
      FLASK_APP: app.py
    volumes:
      - ./track_service:/app
      - ./track_service/media:/app/media
      - ./track_service/migrations:/app/migrations
    # depends_on:
    #   - track_db
    # command: sh -c "while ! nc -z track_db 5432; do sleep 1; done; python app.py"
    # volumes:
    #   - ./track_service/migrations:/app/migrations
    #   - ./track_service/media:/app/media
  track_db:
    image: postgres:13
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=track_service_db
    ports:
      - "5433:5432"
    volumes:
      - track_service_data:/var/lib/postgresql/data
      - ./track_service/media:/app/media
  cart_service:
    build: ./cart_service
    ports:
      - "5002:5002"
    depends_on:
      - cart_db
    command: sh -c "while ! nc -z cart_db 5432; do sleep 1; done; python app.py"
    volumes:
      - ./cart_service/migrations:/app/migrations
  cart_db:
    image: postgres:13
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=cart_service_db
    ports:
      - "5434:5432"
    volumes:
      - cart_service_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - user_service
      - cart_service
      - track_service

volumes:
  user_service_data:
  track_service_data:
  cart_service_data:
  pgadmin-data: