"""Добавлено поле manual_order

Revision ID: 72c5de1320e5
Revises: 3a74abd2a0a3
Create Date: 2025-06-01 13:21:00.705758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72c5de1320e5'
down_revision = '3a74abd2a0a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playlists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manual_order', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playlists', schema=None) as batch_op:
        batch_op.drop_column('manual_order')

    # ### end Alembic commands ###
